package com.example.springapi.send.domain.model;

import lombok.Getter;
import lombok.Builder;
import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.LocalDateTime;

@Getter
@Builder
public class Send {
    
    private final String corpCode;
    private final String processClassCode;
    private final String sendNo;
    private final Integer revisionNo;
    private final String rbType;
    private final String customerCode;
    private final String salesDeptCode;
    private final String salesStaffCode;
    private final LocalDate sendDate;
    private final String printSendNo;
    private final LocalDate collectScheduleDate;
    private final LocalDate taxEffectDate;
    private final String fixType;
    private final String tradeClassifyCode;
    private final String currencyCode;
    private final BigDecimal currencyRate;
    private final Long currencyRateId;
    private final String incotermCodeItem;
    private final String incotermCodeTotal;
    private final LocalDate sellRecordDate;
    private final String cutoffDateCode;
    private final String payCollectDateCodeMonth;
    private final String payCollectDateCodeDate;
    private final String payCollectMethodCode;
    private final Integer billPeriod;
    private final String reckonConditionCode;
    private final String collectNote;
    private final String deliveryReportNote;
    private final String insideNote;
    private final String sendFromWarehouseCode;
    private final LocalDate divideOperationDate;
    private final String divideAfterWarehouseCode;
    private final String warehouseCode;
    private final String deliveryCode;
    private final String deliveryNote;
    private final String carrierCode;
    private final String carrierOrderNote;
    private final LocalDate sendDeliveryOrderReportDate;
    private final String sendDeliveryOrderReportNumber;
    private final String sendDeliveryOrderReportInstructions;
    private final String sourceSendNo;
    private final String shipName;
    private final String voyageNo;
    private final LocalDate shipLeaveDate;
    private final LocalDate shipArriveDate;
    private final LocalDate invoiceCreateDate;
    private final LocalDate blCreateDate;
    private final String loadCountryCode;
    private final String deliveryCountryCode;
    private final String shipPortCode;
    private final String loadPortCode;
    private final String unloadPortCode;
    private final String viaPortCode;
    private final String finalDestinationPortCode;
    private final String consignorCode;
    private final String consignorNote;
    private final String blReceiverCode;
    private final String blReceiverNote;
    private final String arrivalContact1;
    private final String arrivalContact2;
    private final String arrivalContact3;
    private final String shippingCompany;
    private final String shippingBroker;
    private final String overseasCarrierCode;
    private final String bookingNo;
    private final String blCreatePlace;
    private final String blType;
    private final String blTypeOther;
    private final String blPublishQuantity;
    private final String serviceType;
    private final String passPlaceCode;
    private final LocalDate passDate;
    private final LocalDate cutDate;
    private final String informNote;
    private final String freightPayMethodCode;
    private final String sendReportFlagInvoice;
    private final String sendReportFlagPackingList;
    private final String sendReportFlagMillSheet;
    private final String sendReportFlagOthers;
    private final String sendReportOthers;
    private final String blOrderNote;
    private final Long corpBankId;
    private final String shippingAdviceFlagInvoice;
    private final String shippingAdviceFlagPackingList;
    private final String shippingAdviceFlagBl;
    private final String shippingAdviceFlagInsurancePolicy;
    private final String shippingAdviceCountryOfOrigin;
    private final String shippingAdviceFlagMillSheet;
    private final String shippingAdviceFlagCertificateOfAnalysis;
    private final String shippingAdviceFlagTestCertification;
    private final String shippingAdviceFlagCoilList;
    private final String shippingAdviceFlagOthers;
    private final String shippingAdviceOthers;
    private final String customerInformNote;
    private final String m3ReportOutputFlag;
    private final String machiningOrderProcessClassCode;
    private final String machiningOrderNo;
    private final BigDecimal sellAmount;
    private final BigDecimal sellTaxAmount;
    private final BigDecimal baseSellAmount;
    private final BigDecimal baseSellTaxAmount;
    private final BigDecimal dividePackingQuantity;
    private final BigDecimal divideSumReceiveQuantity;
    private final String sealUserCode1;
    private final String sealUserCode2;
    private final String sealUserCode3;
    private final String squareSealFlag;
    private final LocalDateTime latestDeliveryReportOutputDatetime;
    private final String signatureUserCode;
    private final String signatureTitleCode;
}
